version: '3.6'
services:
  baymax:
    container_name: baymax
    ports:
      - 6006:6006
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'tensorboard --host 0.0.0.0 --logdir /tmp/tflearn_logs/'
    volumes:
      - .:/app
